### ISSUE TITLE
AttributeError: 'ToBaselinesVecEnv' object has no attribute 'seed'

### ISSUE THREAD

**Issue by huang-fuxian** [facebookresearch/level-replay#4]
Hello, when I run the example training case, this error appears.  I carefully check all the wrappers, like VecExtractDictObs,VecMonitor,VecNormalize, but did not find the seed() for venv.

**Comment by NasikNafi** [comment]
@huang-fuxian How did you solve this issue? I am getting the same error.

**Comment by Muqing7783** [comment]
How to solve？

**Comment by minqi** [comment]
Please read the Requirements section in the README.md. It lists the commands needed to build the correct Procgen implementation that includes the fast seeding API.
